txgo: ImageUtil.o TextUtil.o Track.o map.o GenericTimer.o drive.o main.o
	cc -framework GLUT -framework OpenGL -o txgo ./lib/libglpng.MACOSX.a ImageUtil.o TextUtil.o Track.o map.o GenericTimer.o drive.o main.o

.c.o: 
	cc -c $< -I. -Wall

run: txgo
	./txgo
	
clean:
	rm -f *.o *.c~ *.h~ txgo
